gladly-team/tab-web

- next.config.js
- src/pages/index.js
merged the last pr into dev to test, here's a record of our previous convo
We'll need this to work for our dev/prod domains, too. Let's just include the following, hardcoded:
https://dev-tab2017.gladly.io/newtab/.*
https://tab.gladly.io/newtab/.*
You can test by merging into the dev branch and making sure all works as expected on dev.
@amaliwanag2 amaliwanag2 22 minutes ago Author Member
@kmjennison I believe that the VERCEL_URL will resolve to those values at each of those environments
@amaliwanag2 amaliwanag2 22 minutes ago Author Member
testing now on dev
> TFAC-100: limit SW caching to our domains

- src/components/UserBackgroundImage.js
> keep array at 2

- src/pages/index.js
it was this easy, i just needed to set overflow to auto so that the scrollbar only comes out when needed
> fix overflow with auto

- src/components/OnboardingFlow.js
can no longer get any cropping at 500%
> add overflow to card and card content

- src/__tests__/pages/account.test.js
- src/pages/account.js
And add more information about what happens when a user chooses to revert.
> [TFAC-316] Make reverting to Tab Legacy an advanced option

- src/pages/beta-opt-in.js
- src/pages/index.js
Reverts gladly-team/tab-web#167
> Revert "set cookie if v4betaEnabled is false"

- src/__tests__/pages/index.test.js
- src/pages/beta-opt-in.js
- src/pages/index.js
Reverts gladly-team/tab-web#169
looked over both PRs.  reverting should do the trick
> Revert "Alec/tfac 377" Undo switching between v4 and legacy based on cookie, TFAC-428

- src/components/UserImpact.js
- src/components/UserImpactContainer.js
- src/components/__tests__/UserImpact.test.js
- src/schema/schema.graphql
- src/utils/__tests__/localstorage-mgr.test.js
- src/utils/constants.js
- src/utils/localstorage-mgr.js
@kmjennison let's make adding copy a separate ticket
> TFAC-445 add cat day logic

- src/components/missionComponents/CurrentMission.js
- src/components/missionComponents/__tests__/CurrentMission.test.js
using use previous sometimes led to restartmission being called with an undefined mission id
> fix restart mission

- src/utils/__tests__/relayEnvironment.test.js
- src/utils/relayEnvironment.js
Debugging https://gladlyteam.atlassian.net/browse/TFAC-306
We might have an error in managing our Relay environment in which the Relay environment updates (with a refreshed AuthUser) _after_ we make requests via Relay. This PR tests that hypothesis by getting an ID token directly in the Relay fetcher.
> Debugging: get a user ID token directly from Firebase for fetch

- src/components/InviteFriendsIcon.js
- src/components/UserImpact.js
> even button spacing

- src/components/CauseIcon.js
- src/components/ImpactCounter.js
- src/components/UserImpact.js
- src/schema/schema.graphql
- src/utils/constants.js
* Add tree icon
* Make cause GIF optional
* Support plural "claimedReferralImpact" in referralRewardTitle
> Support trees cause; make impact and onboarding more flexible

- src/components/CauseIcon.js
- src/components/EmailInviteDialog.js
- src/components/Notification.stories.jsx
- src/components/SettingsPage.js
- src/components/UserImpact.js
- src/components/__tests__/SettingsPage.test.js
* Copy tweak, "Hooray" --> "Hooray!"
* Center the image in the share modal
* Fix broken styles in the TeamSeas icon
* Fix a bug when switching between some causes
> Various edits to the UX

- src/__tests__/pages/account.test.js
This test has been failing for me consistently, so I actually fixed it.
> Fix Account Test

- src/components/SearchInput.js
- src/components/SearchInput.stories.jsx
- src/components/SearchInputContainer.js
- src/components/SearchSelect.js
- src/components/SearchSelect.stories.jsx
- src/components/__tests__/SearchInput.test.js
- src/components/__tests__/SearchSelect.test.js
- src/schema/schema.graphql
- src/utils/mutations/SetUserSearchEngineMutation.js
Do not merge until backend changes are deployed:
https://github.com/gladly-team/tab/pull/1262
Re-run E2E tests when the schema is deployed to QA/prod.
Update the client to use the new Search for a Cause URL that adds aggregated reporting dimensions to the URL.
> Use new search URL for Search for a Cause

- package.json
- src/components/SearchForACauseSellModal.js
- src/components/SearchForACauseSellNotification.js
- src/components/SfacActivityNotification.js
- src/components/SfacExtensionSellNotification.js
- src/components/groupImpactComponents/GroupGoalNotification.js
- src/pages/_app.js
- src/pages/index.js
- src/utils/theme.js
- yarn.lock
This should be on dev for testing!
> Change Font-Family to Poppins/Roboto

- package.json
- src/pages/_document.js
- yarn.lock
Fixes:
https://sentry.io/organizations/gladly-inc/issues/3275981018/?project=5258438
> Upgrade Next.js from 10.0.5 to 10.2.3 to fix Safari error

- src/components/VerticalLinearProgress.js
- src/components/VerticalLinearProgress.stories.jsx
- src/components/__tests__/VerticalLinearProgress.test.js
Note that the markers aren't pixel-perfect accurate (e.g. try 25/50/75 to see how it hits the markers), but I figured for our purposes it's not a huge deal. Let me know if you want me to adjust @kmjennison!
> TFAC-990: VerticalLinearProgress UI Element

- src/utils/__tests__/localStorageFeaturesManager.test.js
- src/utils/localStorageFeaturesManager.js
Should fix https://sentry.io/organizations/gladly-inc/issues/3709475041/?alert_rule_id=10737608&alert_timestamp=1667537417277&alert_type=email&environment=production&project=5258438&referrer=alert_email
> TFAC-1169 Fixing localStorageFeaturesManager

- src/utils/__tests__/adHelpers.test.js
- src/utils/adHelpers.js
> TFAC-1170 Hiding third ad if Screen Too Small

- src/components/VerticalLinearProgress.js
- src/components/groupImpactComponents/GroupImpactSidebar.js
- src/components/groupImpactComponents/GroupImpactSidebar.stories.jsx
- src/components/groupImpactComponents/__tests__/GroupImpactSidebar.test.js
First pass on the GroupImpactSidebar. I'll include animations in a later PR. Also would like your feedback on what the "collapse sidebar" button should look like (hover, how big the button should be, etc).
> TFAC-1018 GroupImpactSidebar pt.1 (Excluding Animations)

- src/components/VerticalLinearProgress.js
- src/components/groupImpactComponents/GroupImpactSidebar.js
- src/components/groupImpactComponents/__tests__/GroupImpactSidebar.test.js
Just need to add one more, the open <-> close animations.
> TFAC-1018 Hover Animation for GroupImpactSidebar

- src/components/groupImpactComponents/GroupImpact.js
- src/components/groupImpactComponents/GroupImpact.stories.jsx
- src/components/groupImpactComponents/GroupImpactContainer.js
- src/components/groupImpactComponents/GroupImpactSidebar.js
- src/components/groupImpactComponents/GroupImpactSidebar.stories.jsx
- src/components/groupImpactComponents/__tests__/GroupImpact.test.js
- src/components/groupImpactComponents/__tests__/GroupImpactContainer.test.js
- src/components/groupImpactComponents/__tests__/GroupImpactSidebar.test.js
- src/schema/schema.graphql
Just sets up the basic `GroupImpact` and `GroupImpactContainer` components, which will eventually contain the `Celebration`, `GroupGoalNotification` and `GroupImpactSidebar` components.
> TFAC-1004: Skeleton Component for integrating GroupImpactSidebar

- src/components/groupImpactComponents/GroupImpactSidebar.js
- src/components/groupImpactComponents/GroupImpactSidebar.stories.jsx
- src/components/groupImpactComponents/__tests__/GroupImpactSidebar.test.js
@kmjennison One question for you, upon clicking the Next Goal Button the bar drains from full to whatever the current goal is at. I think in the mock the bar fills from 0 upon switching to the new goal. Any opinions on this?
> TFAC-1018 Adding Switch Goal Fade Animation

- src/components/groupImpactComponents/GroupImpact.js
- src/components/groupImpactComponents/GroupImpact.stories.jsx
- src/components/groupImpactComponents/GroupImpactSidebar.js
- src/components/groupImpactComponents/GroupImpactSidebar.stories.jsx
- src/components/groupImpactComponents/__tests__/GroupImpact.test.js
- src/components/groupImpactComponents/__tests__/GroupImpactSidebar.test.js
- src/utils/__tests__/localstorage-mgr.test.js
- src/utils/constants.js
- src/utils/localstorage-mgr.js
The changes to `GroupImpactSidebar` were undoing an accidental revert in commit 95a666c5c22539ed2102b5b8d37295144707af9f.
> TFAC-1004 Wiring up GroupImpactSidebar in GroupImpact

- src/pages/_document.js
Installs the js software snippet for getadmiral.com in the head of the index.
> Installed js for getadmiral.com

- src/pages/index.js
This pull requests removes the Jan 2023 SFAC notification and adds the new Feb2023 notification.
In Jan we voted on which cause to support. This notification announces the winner.
> Removed Jan2023 notification and added Feb2023

- src/pages/index.js
Made ads zindex below all other content.
> [TFAC-1215] Hide 3rd app when notifications are up.

- src/components/groupImpactComponents/GroupImpactSidebar.js
https://gladly-team.slack.com/archives/C04MB5E7D6V/p1677017846877489
> Adjusting GroupImpactSidebar Copy

- src/__tests__/pages/about.test.js
- src/components/AboutTheCause.js
- src/components/groupImpactComponents/AboutTheNonprofit.js
- src/components/groupImpactComponents/ImpactMetricList.js
- src/pages/about.js
- src/schema/schema.graphql
About the Cause Changes will go live after this PR
> TFAC-1172 Integration PR

- src/components/groupImpactComponents/GroupImpactSidebar.js
Causes a weird bug when it shows next to the search upsell.
> Update GroupImpactSidebar.js Margin

- .storybook/preview.js
We currently have a bug where lack of installed GA on storybook makes it so that some interactions with storybook components doesn't work. This fixes that.
> Fixing Storybook / Gtag Bug

- src/pages/index.js
This launches our Aug survey notification to our users.
> Launched our Aug survey notification.
